### ISSUE TITLE
Vendoring

### ISSUE THREAD

**Issue by fntlnz** [gianarb/lb#30]
Steady makes use of `github.com/gorilla/mux`.
Since it's an external depdendency I suggest to vendor those packages.

Godep is a good tool for the job: https://github.com/tools/godep

You got a cat with this issue:

![318](https://cloud.githubusercontent.com/assets/3083633/14799216/b6aa7136-0b3b-11e6-8348-ad62ce842f20.gif)

**Comment by gianarb** [comment]
👍  good!
